name: 'Build React'
description: 'Build an React application. Intended to be used in conjunction with -deploy, and -test.'

inputs:
  repository:
    description: 'Which repository are we building?'
    required: true
  app-name:
    description: 'App name. Used for param store lookups.'
    required: true
  target-environment:
    description: 'Where are we deploying this?'
    required: true
    default: 'None'
  token:
    description: 'The github token to authenticate with'
    required: true       
  aws-build-role:
    description: 'The relevant dev build role for AWS stuff.'
    required: true
  aws-access-key-id:
    description: 'AWS access key!'
    required: true
  aws-secret-access-key:
    description: 'AWS access key, but more secreter!'
    required: true
  aws-region:
    description: 'Regionality of the AWS credentialing'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-build-role }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        persist-credentials: false
    - name: Setup Node    
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Inject insteadOf configuration
      shell: bash
      run: |
        git config --global url."https://${{ inputs.token }}@github.com/".insteadOf ssh://git@github.com/
        npm ci    
    - name: Get App Config
      uses: source-ip/actions-aws-ssm-get-by-path@v1
      with:
        paths: ${{ format('/app/{0}/env/{1}/', inputs.app-name, inputs.target-environment) }}
        save-to-environment: true
        file: .env

    - name: Set environment name
      shell: bash
      run: |
        echo "" >> .env
        echo "APP_ENV_NAME=$APP_ENV_NAME" >> .env
    - name: Build React App
      shell: bash
      run: npm install && npm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: client
        path: dist